//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synnduit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synnduit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} attribute can only be applied to one property per class/entity type (invalid class: {1})..
        /// </summary>
        internal static string AmbiguousIdentifierProperty {
            get {
                return ResourceManager.GetString("AmbiguousIdentifierProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ambiguous source system entity ID/destination system entity ID mapping detected in systems with shared identifiers when attempting to resolve the ID of a referenced entity. (Entity Type: &apos;{0}&apos;, Property: &apos;{1}&apos;, Source System ID: &apos;{2}&apos;).
        /// </summary>
        internal static string AmbiguousReferenceIdentifer {
            get {
                return ResourceManager.GetString("AmbiguousReferenceIdentifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache feed represented by type &apos;{0}&apos; could not be found; it may not exist or the type name may be ambiguous; see inner exception for details..
        /// </summary>
        internal static string CacheFeedNotFound {
            get {
                return ResourceManager.GetString("CacheFeedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache has not been initialized..
        /// </summary>
        internal static string CacheNotInitialized {
            get {
                return ResourceManager.GetString("CacheNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A different source system entity ID has been registered for last access correlation ID update..
        /// </summary>
        internal static string CannotChangeCorrelationIdUpdateSourceSystemEntityId {
            get {
                return ResourceManager.GetString("CannotChangeCorrelationIdUpdateSourceSystemEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property name cannot be extracted from the specified lambda expression..
        /// </summary>
        internal static string CannotExtractPropertyName {
            get {
                return ResourceManager.GetString("CannotExtractPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A destination system entity cannot be rejected..
        /// </summary>
        internal static string CannotRejectDestinationSystemEntity {
            get {
                return ResourceManager.GetString("CannotRejectDestinationSystemEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityIdentifier cast operator threw an exception; see inner exception for details..
        /// </summary>
        internal static string CastOperatorThrewException {
            get {
                return ResourceManager.GetString("CastOperatorThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source system entity ID exists in multiple compatible entity types. (Property: &apos;{0}&apos;, Source System ID: &apos;{1}&apos;).
        /// </summary>
        internal static string CompatibleEntityTypeReferenceIdentifierConflict {
            get {
                return ResourceManager.GetString("CompatibleEntityTypeReferenceIdentifierConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application configuration is not available..
        /// </summary>
        internal static string ConfigurationNotAvailable {
            get {
                return ResourceManager.GetString("ConfigurationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context is not available..
        /// </summary>
        internal static string ContextNotAvailable {
            get {
                return ResourceManager.GetString("ContextNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from &apos;{0}&apos; to EntityIdentifier is not supported..
        /// </summary>
        internal static string ConversionFromNotSupported {
            get {
                return ResourceManager.GetString("ConversionFromNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from EntityIdentifier to &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ConversionToNotSupported {
            get {
                return ResourceManager.GetString("ConversionToNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition of the dependency injection container has failed; see inner exception for details..
        /// </summary>
        internal static string DependencyInjectionContainerCompositionFailed {
            get {
                return ResourceManager.GetString("DependencyInjectionContainerCompositionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of a deployment step resulted in an exception; see inner exception for details..
        /// </summary>
        internal static string DeploymentStepFailed {
            get {
                return ResourceManager.GetString("DeploymentStepFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination system entity ID returned by the metadata provider has changed from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string DestinationSystemEntityIdChanged {
            get {
                return ResourceManager.GetString("DestinationSystemEntityIdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination system ID of the specified entity is not set..
        /// </summary>
        internal static string DestinationSystemEntityIdNotSet {
            get {
                return ResourceManager.GetString("DestinationSystemEntityIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; doesn&apos;t have the property that represents the destination system identifier specified (apply the DestinationSystemIdentifier attribute)..
        /// </summary>
        internal static string DestinationSystemIdentifierPropertyNotFound {
            get {
                return ResourceManager.GetString("DestinationSystemIdentifierPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed represented by &apos;{0}&apos; has an ambiguous specification (attribute) for the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string DuplicateFeedEntityType {
            get {
                return ResourceManager.GetString("DuplicateFeedEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity appears to be a duplicate of an entity that no longer exists in the destination system (ID: &apos;{0}&apos;)..
        /// </summary>
        internal static string DuplicateOfNonexistentEntity {
            get {
                return ResourceManager.GetString("DuplicateOfNonexistentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; duplication rule has returned a null reference for the collection of duplicates..
        /// </summary>
        internal static string DuplicationRuleReturnedNull {
            get {
                return ResourceManager.GetString("DuplicationRuleReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has no source system entity identifier..
        /// </summary>
        internal static string EntityHasNoSourceSystemEntityId {
            get {
                return ResourceManager.GetString("EntityHasNoSourceSystemEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type represented by &apos;{0}&apos; is defined multiple times..
        /// </summary>
        internal static string EntityTypeDefinedMultipleTimes {
            get {
                return ResourceManager.GetString("EntityTypeDefinedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity type definition type has illegal generic arguments..
        /// </summary>
        internal static string EntityTypeDefinitionHasGenericArguments {
            get {
                return ResourceManager.GetString("EntityTypeDefinitionHasGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity type definition implements the &apos;{1}&apos; interface multiple times..
        /// </summary>
        internal static string EntityTypeDefinitionImplementsInterfaceMultipleTimes {
            get {
                return ResourceManager.GetString("EntityTypeDefinitionImplementsInterfaceMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos;, specified as the destination system for the entity type represented by &apos;{1}&apos;, doesn&apos;t represent an external system..
        /// </summary>
        internal static string EntityTypeDestinationSystemDoesNotExist {
            get {
                return ResourceManager.GetString("EntityTypeDestinationSystemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity type (ID = &apos;{0:d}&apos;) could not be found..
        /// </summary>
        internal static string EntityTypeIdNotFound {
            get {
                return ResourceManager.GetString("EntityTypeIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type ID of &apos;{0:d}&apos; is not unique..
        /// </summary>
        internal static string EntityTypeIdNotUnique {
            get {
                return ResourceManager.GetString("EntityTypeIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type name of &apos;{0}&apos; is not unique..
        /// </summary>
        internal static string EntityTypeNameNotUnique {
            get {
                return ResourceManager.GetString("EntityTypeNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type names must be unique..
        /// </summary>
        internal static string EntityTypeNamesMustBeUnique {
            get {
                return ResourceManager.GetString("EntityTypeNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of &apos;{0}&apos; set for the &apos;{1}&apos; entity type exceeds the maximum length of {2} characters..
        /// </summary>
        internal static string EntityTypeNameTooLong {
            get {
                return ResourceManager.GetString("EntityTypeNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity type has its name set to a white space value..
        /// </summary>
        internal static string EntityTypeNameWhiteSpace {
            get {
                return ResourceManager.GetString("EntityTypeNameWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity type (&apos;{0}&apos;) could not be found; it may not exist or the name may be ambiguous; see inner exception for details..
        /// </summary>
        internal static string EntityTypeNotFound {
            get {
                return ResourceManager.GetString("EntityTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity type registered for &apos;{0}&apos;..
        /// </summary>
        internal static string EntityTypeNotRegistered {
            get {
                return ResourceManager.GetString("EntityTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event receiver has thrown an exception; see inner exception for details..
        /// </summary>
        internal static string EventReceiverThrewException {
            get {
                return ResourceManager.GetString("EventReceiverThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified lambda expression does not represent a property..
        /// </summary>
        internal static string ExpressionDoesNotRepresentProperty {
            get {
                return ResourceManager.GetString("ExpressionDoesNotRepresentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified external system (ID = &apos;{0:d}&apos;) could not be found..
        /// </summary>
        internal static string ExternalSystemIdNotFound {
            get {
                return ResourceManager.GetString("ExternalSystemIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external system ID of &apos;{0:d}&apos; is not unique..
        /// </summary>
        internal static string ExternalSystemIdNotUnique {
            get {
                return ResourceManager.GetString("ExternalSystemIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external system name of &apos;{0}&apos; is not unique..
        /// </summary>
        internal static string ExternalSystemNameNotUnique {
            get {
                return ResourceManager.GetString("ExternalSystemNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external system names must be unique..
        /// </summary>
        internal static string ExternalSystemNamesMustBeUnique {
            get {
                return ResourceManager.GetString("ExternalSystemNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of &apos;{0}&apos; set for the external system represented by &apos;{1}&apos; exceeds the maximum length of {2} characters..
        /// </summary>
        internal static string ExternalSystemNameTooLong {
            get {
                return ResourceManager.GetString("ExternalSystemNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external system represented by &apos;{0}&apos; has its name set to a white space value..
        /// </summary>
        internal static string ExternalSystemNameWhiteSpace {
            get {
                return ResourceManager.GetString("ExternalSystemNameWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate the generic/non-generic bridge; see inner exception for details..
        /// </summary>
        internal static string FailedToInstantiateBridge {
            get {
                return ResourceManager.GetString("FailedToInstantiateBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed represented by &apos;{0}&apos; has at least one entity type specified (in a feed attribute) with no matching interface implementation..
        /// </summary>
        internal static string FeedEntityTypeNotImplemented {
            get {
                return ResourceManager.GetString("FeedEntityTypeNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; representing a feed has more than one default feed attribute..
        /// </summary>
        internal static string FeedHasMoreThanOneDefaultAttribute {
            get {
                return ResourceManager.GetString("FeedHasMoreThanOneDefaultAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed represented by type &apos;{0}&apos; could not be found; it may not exist or the type name may be ambiguous; see inner exception for details..
        /// </summary>
        internal static string FeedNotFound {
            get {
                return ResourceManager.GetString("FeedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feed is registered for entity type &apos;{0}&apos; and source system &apos;{1}&apos;..
        /// </summary>
        internal static string FeedNotRegistered {
            get {
                return ResourceManager.GetString("FeedNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element in the collection of entities returned by the feed is a null reference..
        /// </summary>
        internal static string FeedReturnedCollectionWithNullElement {
            get {
                return ResourceManager.GetString("FeedReturnedCollectionWithNullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed returned a null reference..
        /// </summary>
        internal static string FeedReturnedNull {
            get {
                return ResourceManager.GetString("FeedReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source system isn&apos;t specified and couldn&apos;t be inferred for the feed represented by &apos;{0}&apos; for the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string FeedSourceSystemNotSpecifiedOrInferable {
            get {
                return ResourceManager.GetString("FeedSourceSystemNotSpecifiedOrInferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source system isn&apos;t specified and couldn&apos;t be inferred for the generic feed represented by &apos;{0}&apos;..
        /// </summary>
        internal static string GenericFeedSourceSystemNotSpecifiedOrInferable {
            get {
                return ResourceManager.GetString("GenericFeedSourceSystemNotSpecifiedOrInferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GetDestinationSystemEntityId method of the metadata provider returned a null reference..
        /// </summary>
        internal static string GetDestinationSystemEntityIdReturnedNull {
            get {
                return ResourceManager.GetString("GetDestinationSystemEntityIdReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GetLabel method of the metadata provider returned a null reference..
        /// </summary>
        internal static string GetLabelReturnedNull {
            get {
                return ResourceManager.GetString("GetLabelReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GetSourceSystemEntityId method of the metadata provider returned a null references..
        /// </summary>
        internal static string GetSourceSystemEntityIdReturnedNull {
            get {
                return ResourceManager.GetString("GetSourceSystemEntityIdReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 index created..
        /// </summary>
        internal static string IndexCreated {
            get {
                return ResourceManager.GetString("IndexCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing the entity cache.
        /// </summary>
        internal static string IndexingCache {
            get {
                return ResourceManager.GetString("IndexingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} indices created..
        /// </summary>
        internal static string IndicesCreatedFormat {
            get {
                return ResourceManager.GetString("IndicesCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IInitializable instance threw an exception; see inner exception for details..
        /// </summary>
        internal static string InitializableThrewException {
            get {
                return ResourceManager.GetString("InitializableThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access initialization context: Initialization events for this instance are suppressed..
        /// </summary>
        internal static string InitializationEventsSuppressed {
            get {
                return ResourceManager.GetString("InitializationEventsSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; doesn&apos;t implement the &apos;{1}&apos; interface in a legal way..
        /// </summary>
        internal static string InterfaceImplementedIllegally {
            get {
                return ResourceManager.GetString("InterfaceImplementedIllegally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CLR type for the entity type &apos;{0}&apos; (&apos;{1}&apos;) could not be loaded..
        /// </summary>
        internal static string InvalidEntityType {
            get {
                return ResourceManager.GetString("InvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not represent a valid {1} value..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not represent a valid garbage collection behavior..
        /// </summary>
        internal static string InvalidGarbageCollectionBehavior {
            get {
                return ResourceManager.GetString("InvalidGarbageCollectionBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; doesn&apos;t have a valid generic feed attribute: Exactly one feed attribute with the source system and at least one entity type specified expected..
        /// </summary>
        internal static string InvalidGenericFeedAttribute {
            get {
                return ResourceManager.GetString("InvalidGenericFeedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifying the message and/or data isn&apos;t supported when events are suppressed..
        /// </summary>
        internal static string InvalidInitializeParameters {
            get {
                return ResourceManager.GetString("InvalidInitializeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; doesn&apos;t represent a valid message type..
        /// </summary>
        internal static string InvalidMessageType {
            get {
                return ResourceManager.GetString("InvalidMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not represent a valid orphan mapping behavior..
        /// </summary>
        internal static string InvalidOrphanMappingBehavior {
            get {
                return ResourceManager.GetString("InvalidOrphanMappingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy properties must be of the type Nullable&lt;T&gt; where T is the type of the property that the proxy property is a proxy for (invalid class/property: {0}/{1})..
        /// </summary>
        internal static string InvalidProxyPropertyType {
            get {
                return ResourceManager.GetString("InvalidProxyPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The run segment type &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string InvalidSegmentType {
            get {
                return ResourceManager.GetString("InvalidSegmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity merger returned a null reference..
        /// </summary>
        internal static string MergerReturnedNull {
            get {
                return ResourceManager.GetString("MergerReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity merger set the trunk version of the entity to a null reference..
        /// </summary>
        internal static string MergerSetTrunkToNull {
            get {
                return ResourceManager.GetString("MergerSetTrunkToNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple cache feeds are defined for the destination system represented by &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleCacheFeedsDefinedForDestinationSystem {
            get {
                return ResourceManager.GetString("MultipleCacheFeedsDefinedForDestinationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple cache feeds are defined for the &apos;{0}&apos; entity type..
        /// </summary>
        internal static string MultipleCacheFeedsDefinedForEntityType {
            get {
                return ResourceManager.GetString("MultipleCacheFeedsDefinedForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple cache feeds defined for the destination (external) system represented by &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleDestinationSystemCacheFeedsDefined {
            get {
                return ResourceManager.GetString("MultipleDestinationSystemCacheFeedsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sinks defined for the destination (external) system represented by &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleDestinationSystemSinksDefined {
            get {
                return ResourceManager.GetString("MultipleDestinationSystemSinksDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple cache feeds defined for the entity type represented by &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleEntityTypeCacheFeedsDefined {
            get {
                return ResourceManager.GetString("MultipleEntityTypeCacheFeedsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sinks defined for the entity type represented by &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleEntityTypeSinksDefined {
            get {
                return ResourceManager.GetString("MultipleEntityTypeSinksDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple feeds are defined for the &apos;{0}&apos; entity type and the &apos;{1}&apos; source system..
        /// </summary>
        internal static string MultipleFeedsForEntityTypeSourceSystemDefined {
            get {
                return ResourceManager.GetString("MultipleFeedsForEntityTypeSourceSystemDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sinks are defined for the destination system represented by &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleSinksDefinedForDestinationSystem {
            get {
                return ResourceManager.GetString("MultipleSinksDefinedForDestinationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sinks are defined for the &apos;{0}&apos; entity type..
        /// </summary>
        internal static string MultipleSinksDefinedForEntityType {
            get {
                return ResourceManager.GetString("MultipleSinksDefinedForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple feeds exist for the source system represented by &apos;{0}&apos; and the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string MultipleSourceSystemEntityTypeFeeds {
            get {
                return ResourceManager.GetString("MultipleSourceSystemEntityTypeFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attribute exists for the feed represented by &apos;{0}&apos; and the &apos;{1}&apos; entity type, nor is a default feed attribute specified..
        /// </summary>
        internal static string NoFeedAttributeForEntityType {
            get {
                return ResourceManager.GetString("NoFeedAttributeForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source system is specified or inferable for the feed represented by &apos;{0}&apos; and the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string NoFeedSourceSystemForEntityType {
            get {
                return ResourceManager.GetString("NoFeedSourceSystemForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sink exists for the &apos;{0}&apos; entity type..
        /// </summary>
        internal static string NoSinkExistsForEntityType {
            get {
                return ResourceManager.GetString("NoSinkExistsForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sink type specified for the &apos;{0}&apos; entity type..
        /// </summary>
        internal static string NoSinkTypeSpecified {
            get {
                return ResourceManager.GetString("NoSinkTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation is currently in progress..
        /// </summary>
        internal static string OperationInProgress {
            get {
                return ResourceManager.GetString("OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation is currently in progress..
        /// </summary>
        internal static string OperationNotInProgress {
            get {
                return ResourceManager.GetString("OperationNotInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{1}&apos; (class: {0}) isn&apos;t readable..
        /// </summary>
        internal static string PropertyMustBeReadable {
            get {
                return ResourceManager.GetString("PropertyMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entity properties and/or reference identifiers must be both readable and writable (invalid class/property: {0}/{1})..
        /// </summary>
        internal static string PropertyMustBeReadableAndWritable {
            get {
                return ResourceManager.GetString("PropertyMustBeReadableAndWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{1}&apos; could not be found (class: {0})..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only value type properties can have nullable proxies (invalid class/property: {0}/{1})..
        /// </summary>
        internal static string PropertyNotValueType {
            get {
                return ResourceManager.GetString("PropertyNotValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} repository method returned a blank parameter name..
        /// </summary>
        internal static string RepositoryMethodReturnedEmptyParameterName {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedEmptyParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity mapping instance returned by the {0} repository method isn&apos;t valid..
        /// </summary>
        internal static string RepositoryMethodReturnedInvalidEntityMapping {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedInvalidEntityMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type instance returned by the {0} repository method isn&apos;t valid..
        /// </summary>
        internal static string RepositoryMethodReturnedInvalidEntityType {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedInvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external system instance returned by the {0} repository method isn&apos;t valid..
        /// </summary>
        internal static string RepositoryMethodReturnedInvalidExternalSystem {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedInvalidExternalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapped entity identifier instance returned by the {0} repository method isn&apos;t valid..
        /// </summary>
        internal static string RepositoryMethodReturnedInvalidMappedEntityIdentifier {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedInvalidMappedEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter instance returned by the {0} repository method isn&apos;t valid..
        /// </summary>
        internal static string RepositoryMethodReturnedInvalidParameter {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shared identifier source system instance returned by the {0} repository method isn&apos;t valid..
        /// </summary>
        internal static string RepositoryMethodReturnedInvalidSharedIdentifierSourceSystem {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedInvalidSharedIdentifierSourceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} repository method returned a null reference parameter value..
        /// </summary>
        internal static string RepositoryMethodReturnedNullParameterValue {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedNullParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} repository method returned a null reference..
        /// </summary>
        internal static string RepositoryMethodReturnedNullReference {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} repository method returned a null reference collection element..
        /// </summary>
        internal static string RepositoryMethodReturnedNullReferenceElement {
            get {
                return ResourceManager.GetString("RepositoryMethodReturnedNullReferenceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} repository method threw an exception..
        /// </summary>
        internal static string RepositoryMethodThrewException {
            get {
                return ResourceManager.GetString("RepositoryMethodThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred during the run; see inner exception for details..
        /// </summary>
        internal static string RunExceptionMessage {
            get {
                return ResourceManager.GetString("RunExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified run (&apos;{0}&apos;) could not be found in the specified configuration file; it may not exist or the name may be ambiguous; see inner exception for details..
        /// </summary>
        internal static string RunNotFound {
            get {
                return ResourceManager.GetString("RunNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serializer has returned a null reference..
        /// </summary>
        internal static string SerializerReturnedNull {
            get {
                return ResourceManager.GetString("SerializerReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A source (external) system cannot share identifiers for an entity type with itself (source system IDs must be unique within each group of source sytems that share identifiers)..
        /// </summary>
        internal static string SharedIdentifierSourceSystemIdsMustBeUnique {
            get {
                return ResourceManager.GetString("SharedIdentifierSourceSystemIdsMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one SharedSourceSystemIdentifiersAttribute instance applied to a type that is neither an entity type nor an entity type definition..
        /// </summary>
        internal static string SharedSourceSystemIdentifiersAttributeAppliedToInvalidType {
            get {
                return ResourceManager.GetString("SharedSourceSystemIdentifiersAttributeAppliedToInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sink represented by type &apos;{0}&apos; could not be found; it may not exist or the type name may be ambiguous; see inner exception for details..
        /// </summary>
        internal static string SinkNotFound {
            get {
                return ResourceManager.GetString("SinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each source (external) system can only share identifiers for a given entity type with one group of external systems..
        /// </summary>
        internal static string SourceSystemCannotShareIdentifiersWithMultipleGroups {
            get {
                return ResourceManager.GetString("SourceSystemCannotShareIdentifiersWithMultipleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each source (external) system can only share identifiers for a given entity type with one group of other systems. Duplicate combination (entity type ID/source system ID): {0:d}/{1:d}.
        /// </summary>
        internal static string SourceSystemCanOnlyShareIdentifiersWithOneGroup {
            get {
                return ResourceManager.GetString("SourceSystemCanOnlyShareIdentifiersWithOneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source system entity ID returned by the metadata provider has changed from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string SourceSystemEntityIdChanged {
            get {
                return ResourceManager.GetString("SourceSystemEntityIdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; doesn&apos;t have the property that represents the source system identifier specified (apply the SourceSystemIdentifier attribute)..
        /// </summary>
        internal static string SourceSystemIdentifierPropertyNotFound {
            get {
                return ResourceManager.GetString("SourceSystemIdentifierPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source system (ID = &apos;{0:d}&apos;) could not be found..
        /// </summary>
        internal static string SourceSystemIdNotFound {
            get {
                return ResourceManager.GetString("SourceSystemIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source system (&apos;{0}&apos;) could not be found; it may not exist or the name may be ambiguous; see inner exception for details..
        /// </summary>
        internal static string SourceSystemNotFound {
            get {
                return ResourceManager.GetString("SourceSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration run segment type requires the source system to be set..
        /// </summary>
        internal static string SourceSystemRequired {
            get {
                return ResourceManager.GetString("SourceSystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least two source (external) systems must be specified for a group of systems that share entity identifiers..
        /// </summary>
        internal static string TooFewSourceSystemsInGroup {
            get {
                return ResourceManager.GetString("TooFewSourceSystemsInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is both a non-generic feed and a generic feed..
        /// </summary>
        internal static string TypeCannotBeBothNonGenericAndGenericFeed {
            get {
                return ResourceManager.GetString("TypeCannotBeBothNonGenericAndGenericFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string TypeDoesNotImplementInterface {
            get {
                return ResourceManager.GetString("TypeDoesNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent an entity type..
        /// </summary>
        internal static string TypeDoesNotRepresentEntityType {
            get {
                return ResourceManager.GetString("TypeDoesNotRepresentEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent an external system..
        /// </summary>
        internal static string TypeDoesNotRepresentExternalSystem {
            get {
                return ResourceManager.GetString("TypeDoesNotRepresentExternalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered entity type is compatible with (i.e., assignable from) the specified CLR type (&apos;{0}&apos;)..
        /// </summary>
        internal static string TypeHasNoCompatibleEntityTypes {
            get {
                return ResourceManager.GetString("TypeHasNoCompatibleEntityTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent a cache feed..
        /// </summary>
        internal static string TypeNotCacheFeed {
            get {
                return ResourceManager.GetString("TypeNotCacheFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent a cache feed for the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string TypeNotCacheFeedForEntityType {
            get {
                return ResourceManager.GetString("TypeNotCacheFeedForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type type &apos;{0}&apos; does not represent a feed..
        /// </summary>
        internal static string TypeNotFeed {
            get {
                return ResourceManager.GetString("TypeNotFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent a feed for the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string TypeNotFeedForEntityType {
            get {
                return ResourceManager.GetString("TypeNotFeedForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent a sink..
        /// </summary>
        internal static string TypeNotSink {
            get {
                return ResourceManager.GetString("TypeNotSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent a sink for the &apos;{1}&apos; entity type..
        /// </summary>
        internal static string TypeNotSinkForEntityType {
            get {
                return ResourceManager.GetString("TypeNotSinkForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; isn&apos;t valid for the export of the &apos;{1}&apos; interface..
        /// </summary>
        internal static string TypeNotValidForInterfaceExport {
            get {
                return ResourceManager.GetString("TypeNotValidForInterfaceExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve reference identifier. (Property: {0}; Source System ID: &apos;{1}&apos;).
        /// </summary>
        internal static string UnableToResolveReferenceIdentifier {
            get {
                return ResourceManager.GetString("UnableToResolveReferenceIdentifier", resourceCulture);
            }
        }
    }
}
